# Generated by Django 5.0.2 on 2024-03-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Telegram ID'),
        ),
    ]
