version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    restart: always
    ports:
    - "5432:5432"

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
    environment:
#      - REDIS_PASSWORD=my-password
      - REDIS_PORT=6379

volumes:
  postgres_data:
