# Generated by Django 5.0.2 on 2024-03-10 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='is_positive',
            new_name='is_pleasant',
        ),
    ]
