# Generated by Django 5.0.2 on 2024-03-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_rename_is_positive_habit_is_pleasant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
